name: Check No New Access

on:
  workflow_dispatch # workflow will be triggered manually

jobs:
  check-no-new-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run IAM Access Analyzer Check (No New Access)
        run: |
          aws accessanalyzer check-no-new-access \
            --policy-type IDENTITY_POLICY \
            --current-policy file://policies/example_new_policy.json \
            --previous-policy file://policies/example_old_policy.json
