name: Check No Public Access (Fail Build in case of issues)

on:
  workflow_dispatch # workflow will be triggered manually

jobs:
  check-no-public-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run IAM Access Analyzer Check (No Public Access)
        run: |
          # Below you can find an example workflow that will fail the build if
          # IAM Access Analyzer detected issues within the submitted policy
          aws accessanalyzer check-no-public-access \
            --policy-document file://policies/public_resource_policy.json \
            --resource-type AWS::S3::Bucket > output.json
          INSPECTION_RES=$(cat output.json | grep "FAIL")
          if [ "$INSPECTION_RES" != "" ]; then
            echo "Issues detected during analysis, details: $(cat output.json)" && exit 1
          else
            echo "Not detected issues with the submitted policy"
          fi
