name: Check Access Not Granted Positive

on:
  workflow_dispatch # workflow will be triggered manually

jobs:
  check-access-not-granted:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run IAM Access Analyzer Check (Access Not Granted)
        run: |
          aws accessanalyzer check-access-not-granted \
            --policy-type IDENTITY_POLICY \
            --policy file://policies/example_new_policy.json \
            --access-constraint "action=sts:AssumeRole,principal=*"
